Category.create(name: "Books")
Category.create(name: "Movies")
Category.create(name: "Home & Garden")
Category.create(name: "Beauty & Health")
Category.create(name: "Clothing")

Product.create(name: "Harry Potter and the Sorcerer's Stone", description: "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards, and he begins to discover some clues about his illustrious birthright. From the surprising way he is greeted by a lovable giant, to the unique curriculum and colorful faculty at his unusual school, Harry finds himself drawn deep inside a mystical world he never knew existed and closer to his own noble destiny.", price: 8, category_id: 1)

Product.create(name: "Harry Potter And The Chamber Of Secrets ", description: "The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike. And strike it does. For in Harry's second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls' bathroom, and the unwanted attentions of Ron Weasley's younger sister, Ginny.", price: 7, category_id: 1)

Product.create(name: "Harry Potter and the Prisoner of Azkaban", description: "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort. Now he has escaped, leaving only two clues as to where he might be headed: Harry Potter's defeat of You-Know-Who was Black's downfall as well. And the Azkban guards heard Black muttering in his sleep, \"He's at Hogwarts...he's at Hogwarts.\"", price: 8, category_id: 1)

Product.create(name: "Interstellar", description: "Kip Thorne, the physicist who assisted Christopher Nolan on the scientific aspects of Interstellar, shows us that the movie’s jaw-dropping events and stunning, never-before-attempted visuals are grounded in real science. Thorne shares his experiences working as the science adviser on the film and then moves on to the science itself in chapters on wormholes, black holes, interstellar travel, and much more.", price: 23, category_id: 2)

Product.create(name: "The Hobbit: The Battle of the Five Armies", description: "First off, I'm an absolute Middle Earth fanatic, both on the literary page and on the screen (I've seen and read it all, literally). This is my personal perspective on The Hobbit: The Battle of the Five Armies. And if you visit the comment section, I'll detail what's in the EXTENDED EDITION. So stick with me, dear reader, because this review could be long and fraught with emotion. Let us begin! IMO, BATTLE might just be the best of the Hobbit trilogy. The fans of the book will get their emotional moments, their classic Tolkien lines, and their respect treated seriously, while Peter Jackson reclaims his throne as the living King of Epic, with the Wagnerian grandeur, big feels, and visual splendor he does so well. From the opening moments, wherein Smaug the Terrible rains down an unholy blitzkrieg of dragonfire on unsuspecting Laketown, BATTLE sets a snappy pace and only lets up long enough for you to gasp in awe or dab a tear from your eye. BATTLE is at once the most epic and the most personal of the trilogy. The Company of Thorin have now captured Erebor and are sitting upon a massive hoard of dragon gold. Drawn by riches and power, the forces of good and evil converge upon the Lonely Mountain. War between elves, dwarves, men, and orcs looms fell on the horizon even as darkness creeps into the heart of Thorin Oakenshield, and the Dark Lord Sauron looks to make a comeback.", price: 300, category_id: 2)

Product.create(name: "Fifty Shades of Grey", description: "Fifty Shades of Grey is the hotly anticipated film adaptation of the bestselling book that has become a global phenomenon. Since its release, the “Fifty Shades” trilogy has been translated in 52 languages worldwide and sold more than 90 million copies in e-book and print—making it one of the biggest and fastest-selling book series ever. Stepping into the roles of Christian Grey and Anastasia Steele, who have become iconic to millions of readers, are Jamie Dornan and Dakota Johnson. Joining them in the cast are Luke Grimes as Christian’s brother, Elliot; Victor Rasuk as Anastasia’s close friend, José; and Jennifer Ehle as Anastasia’s mother, Carla. Fifty Shades of Grey is being directed by Sam Taylor-Johnson and produced by Michael De Luca and Dana Brunetti alongside E L James, the creator of the series. The screenplay is by Kelly Marcel, with revisions by Patrick Marber and Mark Bomback.", price: 200, category_id: 2)
